/* GENERATED by tools/extract_cell_motion.py -- do not edit.
 * Canonical source: research/organisms/cell-motion.json.
 * A JS wrapper exists so the no-build web/ runtime can read the
 * measured distributions with no fetch and no JSON loader, and so
 * the headless tests can require() them. */
(function () {
  "use strict";
  var DATA = {
  "_comment": "Measured from the cultured-neuron timelapse by tools/extract_cell_motion.py. Lengths normalised by the frame diagonal; 'frame' = one timelapse step. The sim samples these distributions instead of hand-picked constants. Caveat: soma identities are re-established per step, so 'link_fraction' of blobs survive a step and the measured directional persistence is a LOWER bound -- identity swaps randomise heading. Speed and branch-angle stats are solid.",
  "source": {
    "video": "C:/Users/klaas/Documents/Coding/Personal Projects/Repositories/Deep-House/research/organisms/source/RDT_20260902_131525.mp4",
    "frame_size": [
      914,
      720
    ],
    "video_fps": 30.0,
    "step_seconds": 1.0,
    "steps": 24,
    "extracted": "2026-09-02"
  },
  "somata": {
    "count_per_frame": [
      24,
      30,
      30,
      33,
      38,
      28,
      34,
      37,
      35,
      39,
      38,
      39,
      33,
      32,
      37,
      33,
      33,
      28,
      33,
      28,
      40,
      26,
      28,
      31
    ],
    "count_mean": 32.79,
    "link_fraction": 0.577,
    "migration_speed_px_per_frame": {
      "n": 436,
      "mean": 9.4223,
      "std": 9.2618,
      "median": 6.4996,
      "p10": 0.294,
      "p90": 23.7539
    },
    "migration_speed_norm_per_frame": {
      "n": 436,
      "mean": 0.0081,
      "std": 0.008,
      "median": 0.0056,
      "p10": 0.0003,
      "p90": 0.0204
    },
    "speed_hist_norm": {
      "bin_edges": [
        0.0,
        0.01,
        0.02,
        0.03,
        0.04,
        0.05,
        0.06,
        0.07,
        0.08,
        0.09,
        0.1,
        0.11,
        0.12
      ],
      "counts": [
        274,
        116,
        46,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "directional_persistence_cos": {
      "n": 157,
      "mean": 0.0569,
      "std": 0.7211,
      "median": 0.1259,
      "p10": -0.9665,
      "p90": 0.9525
    },
    "turn_angle_deg": {
      "n": 157,
      "mean": 85.91,
      "std": 54.0924,
      "median": 82.7687,
      "p10": 17.7304,
      "p90": 165.1374
    },
    "turn_hist_deg": {
      "bin_edges": [
        0.0,
        15.0,
        30.0,
        45.0,
        60.0,
        75.0,
        90.0,
        105.0,
        120.0,
        135.0,
        150.0,
        165.0,
        180.0
      ],
      "counts": [
        15,
        18,
        14,
        8,
        13,
        19,
        10,
        15,
        7,
        11,
        11,
        16
      ]
    }
  },
  "filaments": {
    "skeleton_length_px_per_frame": [
      2991,
      2959,
      2680,
      2829,
      3038,
      2875,
      3020,
      3074,
      3119,
      2979,
      2982,
      3045,
      2897,
      3092,
      3052,
      2854,
      3045,
      2863,
      3303,
      3036,
      3116,
      3073,
      3113,
      2815
    ],
    "branch_angle_deg": {
      "n": 9390,
      "mean": 102.5288,
      "std": 43.6216,
      "median": 111.8014,
      "p10": 11.3099,
      "p90": 153.4349
    },
    "branch_angle_hist_deg": {
      "bin_edges": [
        0.0,
        15.0,
        30.0,
        45.0,
        60.0,
        75.0,
        90.0,
        105.0,
        120.0,
        135.0,
        150.0,
        165.0,
        180.0
      ],
      "counts": [
        973,
        116,
        64,
        170,
        595,
        654,
        1666,
        1400,
        1343,
        1397,
        697,
        315
      ]
    },
    "tip_extension_rate_per_frame": {
      "n": 23,
      "mean": -0.0008,
      "std": 0.0624,
      "median": 0.001,
      "p10": -0.0776,
      "p90": 0.0672
    }
  }
};
  if (typeof window !== "undefined") window.CELL_MOTION = DATA;
  if (typeof module !== "undefined" && module.exports) module.exports = DATA;
})();
