/* wiring.js — The Wiring Network: cells that search, touch, lock, and percolate.
 *
 * A second organism class for Deep House. Where the Seed is PACKING (one growth
 * rule, no interaction), this is CONNECTION — autonomous cell-agents that reach
 * out, touch, wire up, migrate, prune, and settle into a living graph.
 *
 * Not a re-skin of organisms.js's Synaptic renderer, and not a duplicate of it
 * either: Synaptic draws signals over a FIXED k-nearest-neighbour graph built
 * once by buildSUB(), so nothing there can ever search, connect, or percolate.
 * This file replaces that constructor with a growth model and keeps the render
 * language (radial-gradient halos, thin filaments, travelling pulses, a palette
 * ramp) so the two read as one house.
 *
 * MEASURED, NOT INVENTED — migration speed, branch angles and tip-extension rate
 * are sampled from web/viz/cell-motion.js, generated by tools/extract_cell_motion.py
 * from the actual cell-culture footage. Where the measurement is weak we say so at
 * the point of use rather than laundering it into a constant (see HEADING below).
 *
 * DETERMINISM (house law) — no bare Math.random anywhere. Placement, branching and
 * connection all draw from ONE seeded rng; the per-cell wander comes from a seeded
 * value-noise field indexed by (nodeId, time), so a replay is identical frame for
 * frame while still looking organic — noise is a FUNCTION of time, not a per-frame
 * draw, so it cannot drift with framerate.
 *
 * HEADLESS SPLIT — all simulation lives in step() and touches arrays only, so the
 * whole arc can be run and asserted under node. Only draw() touches a canvas.
 *
 * Browser (window.WIRING) + bare node (module.exports), same dual-export discipline
 * as organisms.js / palettes.js.
 */
(function () {
  "use strict";
  var root = (typeof window !== "undefined") ? window : globalThis;
  var TAU = Math.PI * 2;

  function clamp(x, a, b) { return x < a ? a : x > b ? b : x; }
  function lerp(a, b, t) { return a + (b - a) * t; }
  function smooth(t) { return t * t * (3 - 2 * t); }
  function mulberry32(a) { return function () { a |= 0; a = a + 0x6D2B79F5 | 0; var t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
  function hexRgb(h) { h = (h || "8E7CC3").replace("#", ""); var n = parseInt(h, 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; }
  function rgba(c, a) { return "rgba(" + (c[0] | 0) + "," + (c[1] | 0) + "," + (c[2] | 0) + "," + a + ")"; }

  // OKLab, so a blend of two cell colours stays vivid.
  // Mixing in sRGB is what makes averaged colours go muddy: the space is not
  // perceptually uniform, so the midpoint of two saturated hues reads darker and
  // greyer than either parent. OKLab (Bjoern Ottosson, 2020) is near-uniform, so a
  // straight lerp there is the blend the eye expects. Cheap: two cube roots.
  function srgbToLin(c) { c /= 255; return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4); }
  function linToSrgb(c) { c = c <= 0.0031308 ? c * 12.92 : 1.055 * Math.pow(c, 1 / 2.4) - 0.055; return clamp(c * 255, 0, 255); }
  function toOklab(v) {
    var r = srgbToLin(v[0]), g = srgbToLin(v[1]), b = srgbToLin(v[2]);
    var l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
    var m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
    var q = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
    return [0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * q,
            1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * q,
            0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * q];
  }
  function fromOklab(lab) {
    var l = lab[0] + 0.3963377774 * lab[1] + 0.2158037573 * lab[2];
    var m = lab[0] - 0.1055613458 * lab[1] - 0.0638541728 * lab[2];
    var q = lab[0] - 0.0894841775 * lab[1] - 1.2914855480 * lab[2];
    l = l * l * l; m = m * m * m; q = q * q * q;
    return [linToSrgb(+4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * q),
            linToSrgb(-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * q),
            linToSrgb(-0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * q)];
  }
  // Mixing along the OKLab STRAIGHT LINE is still not enough: the segment between two
  // different hues passes near the neutral axis, so the midpoint desaturates -- exactly
  // the mud we are avoiding. So we mix in cylindrical OKLCh instead: lightness and
  // chroma lerp, hue takes the SHORT arc. The blend then travels around the colour
  // wheel at full chroma rather than cutting through grey.
  function toOklch(v) {
    var L = toOklab(v);
    return [L[0], Math.sqrt(L[1] * L[1] + L[2] * L[2]), Math.atan2(L[2], L[1])];
  }
  function fromOklch(c) { return fromOklab([c[0], Math.cos(c[2]) * c[1], Math.sin(c[2]) * c[1]]); }
  function hueLerp(h1, h2, t) {
    var d = h2 - h1;
    while (d > Math.PI) d -= TAU;
    while (d < -Math.PI) d += TAU;
    return h1 + d * t;
  }
  function mixOklab(a, b, t) {
    var A = toOklch(a), B = toOklch(b);
    // a near-neutral parent has no meaningful hue of its own -- borrow the other's
    var ha = A[1] < 0.02 ? B[2] : A[2], hb = B[1] < 0.02 ? A[2] : B[2];
    return fromOklch([lerp(A[0], B[0], t), lerp(A[1], B[1], t), hueLerp(ha, hb, t)]);
  }

  // ── vivid(): a hue, rendered as saturated as sRGB will actually hold ──────────
  // ANTI-MUD, second design. The first version bounded the gamut to two anchors; K.
  // found that boring, so cells now spawn across the WHOLE wheel and mud is prevented
  // a different way: colour is never averaged in a rectangular space at all. A cell's
  // colour is a HUE, blends are circular means of hues (below), and the hue is only
  // turned into pixels here -- at a fixed pleasing lightness and the highest chroma
  // that hue can carry inside sRGB. There is no path from two vivid colours to a grey
  // one, because chroma is never an input to the mix.
  var VIVID_L = 0.74;        // OKLab lightness: bright enough to glow on black
  var VIVID_C = 0.17;        // wanted chroma; the real ceiling is per-hue, found below
  var vividCache = {};
  function inGamut(rgbv) {
    for (var q = 0; q < 3; q++) if (rgbv[q] < -0.5 || rgbv[q] > 255.5) return false;
    return true;
  }
  function vivid(h) {
    h = ((h % TAU) + TAU) % TAU;
    var key = Math.round(h * 256 / TAU);
    var hit = vividCache[key];
    if (hit) return hit;
    var hq = key * TAU / 256;
    // binary search the largest in-gamut chroma up to VIVID_C: hue and lightness are
    // honoured exactly, and only the saturation gives, never toward grey by more than
    // sRGB physically requires for that hue.
    var lo = 0, hi = VIVID_C;
    for (var it = 0; it < 12; it++) {
      var mid = (lo + hi) / 2;
      if (inGamut(fromOklchRaw([VIVID_L, mid, hq]))) lo = mid; else hi = mid;
    }
    var out = fromOklch([VIVID_L, lo, hq]);
    vividCache[key] = out;
    return out;
  }
  // fromOklch clamps into 0..255; the gamut probe needs the UNclamped values
  function fromOklchRaw(c) {
    var lab = [c[0], Math.cos(c[2]) * c[1], Math.sin(c[2]) * c[1]];
    var l = lab[0] + 0.3963377774 * lab[1] + 0.2158037573 * lab[2];
    var m = lab[0] - 0.1055613458 * lab[1] - 0.0638541728 * lab[2];
    var q2 = lab[0] - 0.0894841775 * lab[1] - 1.2914855480 * lab[2];
    l = l * l * l; m = m * m * m; q2 = q2 * q2 * q2;
    function toS(c2) { c2 = c2 <= 0.0031308 ? c2 * 12.92 : 1.055 * Math.pow(Math.max(0, c2), 1 / 2.4) - 0.055; return c2 * 255; }
    return [toS(+4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * q2),
            toS(-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * q2),
            toS(-0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * q2)];
  }

  function makeRamp(cols) {
    var n = cols.length;
    return function (t) {
      t = clamp(t, 0, 1) * (n - 1);
      var i = Math.floor(t), f = smooth(t - i), a = cols[i], b = cols[Math.min(n - 1, i + 1)];
      return [a[0] + (b[0] - a[0]) * f, a[1] + (b[1] - a[1]) * f, a[2] + (b[2] - a[2]) * f];
    };
  }

  // ── seeded value noise, indexed by (id, time) ─────────────────────────────────
  // The heading of a wandering cell must be reproducible AND smooth. A per-frame
  // random draw is neither (it jitters, and it changes with framerate). A hash of
  // the integer lattice, smoothly interpolated in t, is both.
  function valueNoise(seed) {
    return function (id, t) {
      var i = Math.floor(t), f = smooth(t - i);
      return lerp(hash2(seed, id, i), hash2(seed, id, i + 1), f);
    };
  }
  function hash2(seed, a, b) {
    var h = (seed ^ Math.imul(a | 0, 0x9E3779B1) ^ Math.imul(b | 0, 0x85EBCA77)) >>> 0;
    h = Math.imul(h ^ h >>> 15, 0x2545F491) >>> 0;
    return ((h ^ h >>> 13) >>> 0) / 4294967296;
  }

  // ── sampling the measured distributions ───────────────────────────────────────
  // A committed histogram is the data contract; this is the only way constants
  // enter the model.
  function sampleHist(h, rnd) {
    if (!h || !h.counts || !h.counts.length) return 0;
    var total = 0, i;
    for (i = 0; i < h.counts.length; i++) total += h.counts[i];
    if (total <= 0) return 0;
    var r = rnd() * total, acc = 0;
    for (i = 0; i < h.counts.length; i++) {
      acc += h.counts[i];
      if (r <= acc) return lerp(h.bin_edges[i], h.bin_edges[i + 1], rnd());
    }
    return h.bin_edges[h.bin_edges.length - 1];
  }
  // Box-Muller, for the stats given as mean/std rather than as a histogram.
  function gauss(rnd, mean, std) {
    var u = Math.max(1e-9, rnd()), v = rnd();
    return mean + std * Math.sqrt(-2 * Math.log(u)) * Math.cos(TAU * v);
  }

  // ── tunables ──────────────────────────────────────────────────────────────────
  // Everything with a biological counterpart is measured; these are the framing
  // choices the footage cannot make for us (how many cells fit the frame, how long
  // a watcher should wait for the payoff).
  var N_CELLS = 74;
  var PLACE_MIN_D = 0.155;   // seeded Poisson-ish spacing, normalised units
  var MAX_TIPS = 5;          // filopodia a cell holds at once
  var TIP_START = 0.012;
  var TIP_MAX = 0.42;        // beyond this a probe has failed and retracts
  var TOUCH_R = 0.042;       // a tip this close to a soma has made contact
  var BRANCH_AT = 0.11;      // tip length at which it may split
  var BRANCH_P = 0.55;
  var EDGE_W_GAIN = 0.55;    // fasciculation: traffic thickens
  var EDGE_W_DECAY = 0.055;  // ...disuse thins
  var EDGE_PRUNE_W = 0.16;   // below this, after the grace window, the edge goes
  var MAX_DEG = 4;           // a cell wires a handful of partners, not the whole field
  var PRUNE_AFTER = 55;      // s — brains overconnect first, prune later
  var SPRING_K = 0.35;
  var REST_LEN = 0.26;
  // Footage time is not watching time: the culture takes hours, the room takes a
  // minute. GROWTH_TEMPO scales the measured rates into the watcher's patience;
  // the SHAPE of every distribution is untouched.
  var GROWTH_TEMPO = 0.075;
  var DRIFT_TEMPO = 6;
  var DEFAULT_PALETTE = ["1b2a4a", "5f7fd6", "b8a9e0", "f2c94c", "ffe9b0"];
  // colour bleed along filaments (see the hue-diffusion block in step())
  var BLEED = 0.42;          // how fast a cell is pulled toward its neighbours' hues
  var ELASTIC = 0.30;        // ...and how hard it holds on to the hue it was born with
  var DOM_LO = 0.35, DOM_HI = 1.0;   // seeded dominance range, allele-style

  // ══════════════════════════════════════════════════════════════════════════════
  function create(seed, motion) {
    seed = seed | 0;
    var rnd = mulberry32(seed);
    var noise = valueNoise(seed ^ 0x5bd1);
    var M = motion || (root.CELL_MOTION || null);
    if (!M) throw new Error("wiring.js needs cell-motion data (web/viz/cell-motion.js)");

    var speedHist = M.somata.speed_hist_norm;
    var branchHist = M.filaments.branch_angle_hist_deg;
    var tipStats = M.filaments.tip_extension_rate_per_frame;
    // The footage nets ~zero growth: filaments extend and retract in balance over
    // the 24 measured seconds. So the extension SCALE is the measured spread, not
    // the measured mean — the mean is a wash by construction, and a growth model
    // driven by it would never grow. Honest use of an honest number.
    var tipRate = Math.max(0.004, Math.abs(tipStats ? tipStats.std : 0.06));

    var nodes = [], edges = [], sig = [], i, j;
    var hueDelta = [];   // scratch for the per-step hue bleed; sized once nodes exist

    // Cells spawn across the WHOLE hue wheel -- a rainbow field, not two populations.
    // Stratified rather than uniform-random: the wheel is cut into N slots, one cell
    // per slot with a seeded jitter inside it, then the slots are dealt out in seeded
    // random order. Uniform draws clump (that is what uniform randomness does), and a
    // clumped wheel reads as two or three colours, which is the complaint this replaces.
    // Stratification guarantees the field is actually rainbow on every seed.
    var hueSlots = [], hi2;
    for (hi2 = 0; hi2 < N_CELLS; hi2++) hueSlots.push((hi2 + rnd()) / N_CELLS * TAU);
    for (hi2 = hueSlots.length - 1; hi2 > 0; hi2--) {     // seeded Fisher-Yates
      var sw = (rnd() * (hi2 + 1)) | 0, tmpH = hueSlots[hi2];
      hueSlots[hi2] = hueSlots[sw]; hueSlots[sw] = tmpH;
    }
    var hueNext = 0;
    function spawnHue() { return hueSlots[hueNext++ % hueSlots.length]; }
    // Dominance, as alleles: a dominant hue pulls its neighbours harder than they pull
    // back, so a recessive cell next to a dominant one does most of the moving. Seeded
    // per cell, so a run's dominance map is as reproducible as its geometry.
    function spawnDom() { return DOM_LO + rnd() * (DOM_HI - DOM_LO); }

    // seeded placement — rejection sampling in the disc, same shape as buildSUB's
    var tries = 0;
    while (nodes.length < N_CELLS && tries < 12000) {
      tries++;
      var a = rnd() * TAU, r = Math.sqrt(rnd()) * 0.92;
      var x = Math.cos(a) * r, y = Math.sin(a) * r, ok = true;
      for (i = 0; i < nodes.length; i++) {
        var dx = nodes[i].x - x, dy = nodes[i].y - y;
        if (dx * dx + dy * dy < PLACE_MIN_D * PLACE_MIN_D) { ok = false; break; }
      }
      if (!ok) continue;
      nodes.push({
        id: nodes.length, x: x, y: y, hx: x, hy: y,   // home, for the spring
        vx: 0, vy: 0, tips: [], deg: 0, fire: 0, refr: 0,
        comp: nodes.length, born: rnd(),              // phase offset so growth isn't in lockstep
        hue: 0, hue0: 0, dom: 0                       // colour: current, born-with, dominance
      });
    }
    for (i = 0; i < nodes.length; i++) {
      nodes[i].hue = nodes[i].hue0 = spawnHue();
      nodes[i].dom = spawnDom();
    }
    for (i = 0; i < nodes.length; i++) hueDelta.push(0);
    for (i = 0; i < nodes.length; i++) seedTips(nodes[i]);

    function seedTips(n) {
      var k = 2 + ((rnd() * (MAX_TIPS - 2)) | 0);
      for (var q = 0; q < k; q++) n.tips.push({ a: rnd() * TAU, len: TIP_START, age: 0, s: rnd() * 1000 });
    }

    // ── colour: a gradient that PERSISTS, not an average ──────────────────────
    // Every cell keeps its OWN hue for the whole run. Colour does not fuse; it BLEEDS
    // along filaments, one hop at a time, strongest where two differently-coloured
    // regions meet and weaker with every hop away from that seam. Two forces, applied
    // every step in step():
    //
    //   bleed   -- each cell eases toward its neighbours' hues along the short arc,
    //              asymmetrically: the pull a cell FEELS is scaled by how dominant its
    //              neighbour is relative to itself, so a recessive cell beside a
    //              dominant one does most of the moving (alleles, not averaging).
    //   elastic -- each cell is also pulled back toward the hue it was born with.
    //
    // The elastic term is why this settles into a GRADIENT instead of marching to one
    // colour. A cell deep inside a like-coloured patch feels almost no bleed (its
    // neighbours already agree) and so stays where it started; a cell at the seam feels
    // the full pull and lands most of the way between. That is the 3-blue/2-red picture:
    // the two at the junction go nearly purple, the next ones shift a little, and the
    // furthest blue stays blue.
    //
    // Deliberately NOT a component-wide average, and deliberately NOT a union-find --
    // the earlier version of this file collapsed each component to one mass-weighted
    // hue, which is the exact opposite property.
    function shortArc(from, to) {           // signed shortest angular distance from->to
      var d = (to - from) % TAU;
      if (d > Math.PI) d -= TAU;
      if (d < -Math.PI) d += TAU;
      return d;
    }
    function hueOf(i) { return nodes[i].hue; }
    // how far a cell has been dragged from the hue it was born with (radians, 0..PI)
    function driftOf(i) { return Math.abs(shortArc(nodes[i].hue0, nodes[i].hue)); }

    var self = {
      seed: seed, motion: M, nodes: nodes, edges: edges, sig: sig,
      t: 0, giant: 0, comps: nodes.length, locks: 0, pruned: 0, percolatedAt: -1,
      bloom: 0,

      // ── simulation: arrays only, safe headless ────────────────────────────────
      step: function (dt) {
        dt = Math.min(dt, 0.05);           // one slow frame must not teleport the culture
        this.t += dt;
        var t = this.t, n, k, e;

        // 1. filopodial search — probes extend, wander, branch, and fail
        for (i = 0; i < nodes.length; i++) {
          n = nodes[i];
          for (k = n.tips.length - 1; k >= 0; k--) {
            var tip = n.tips[k];
            tip.age += dt;
            tip.len += tipRate * GROWTH_TEMPO * dt * (0.6 + noise(n.id * 7 + k, t * 0.5));
            // heading wanders on the seeded field. The footage's own persistence
            // number is a LOWER bound (identities are re-established per step, so
            // swaps randomise heading — flagged in cell-motion.json), so we take
            // the smoothness from the noise field and use the measurement only for
            // the branching angles, which ARE solid.
            tip.a += (noise(n.id * 31 + k, t * 0.7) - 0.5) * 2.2 * dt;

            if (n.deg >= MAX_DEG) {   // satisfied: stop searching, pull the probe back in
              tip.len -= tipRate * GROWTH_TEMPO * dt * 1.4;
              if (tip.len < TIP_START) { n.tips.splice(k, 1); self.pruned++; }
              continue;
            }
            var hit = contact(n, tip);
            if (hit >= 0) { lock(n, nodes[hit]); n.tips.splice(k, 1); continue; }

            if (tip.len > BRANCH_AT && n.tips.length < MAX_TIPS && rnd() < BRANCH_P * dt) {
              var da = sampleHist(branchHist, rnd) * Math.PI / 180;
              n.tips.push({ a: tip.a + (rnd() < 0.5 ? da : -da) * 0.5, len: TIP_START, age: 0, s: rnd() * 1000 });
            }
            // synaptic pruning, the honest beat: an unproductive probe retracts.
            if (tip.len > TIP_MAX) {
              tip.len -= tipRate * GROWTH_TEMPO * dt * 1.6;
              if (tip.len < TIP_START) { n.tips.splice(k, 1); self.pruned++; }
            }
          }
          // a cell that has lost all its probes and is still lonely tries again
          if (n.tips.length === 0 && n.deg < MAX_DEG && rnd() < 0.5 * dt) {
            n.tips.push({ a: rnd() * TAU, len: TIP_START, age: 0, s: rnd() * 1000 });
          }
        }

        // 2. migration — speed sampled from the measured distribution, heading from
        //    the seeded noise field; plus a light spring back toward home and along
        //    formed edges (somata tow their wiring, they don't tear it).
        for (i = 0; i < nodes.length; i++) {
          n = nodes[i];
          var sp = sampleHist(speedHist, rnd) * DRIFT_TEMPO;
          var ang = noise(n.id, t * 0.25) * TAU;
          n.vx += Math.cos(ang) * sp * dt;
          n.vy += Math.sin(ang) * sp * dt;
          n.vx += (n.hx - n.x) * SPRING_K * dt * 0.5;
          n.vy += (n.hy - n.y) * SPRING_K * dt * 0.5;
          n.vx *= 0.90; n.vy *= 0.90;
        }
        for (e = 0; e < edges.length; e++) {
          var ed = edges[e], A = nodes[ed.a], B = nodes[ed.b];
          var ex = B.x - A.x, ey = B.y - A.y, d = Math.hypot(ex, ey) || 1e-6;
          var f = (d - REST_LEN) * SPRING_K * dt / d;
          A.vx += ex * f; A.vy += ey * f; B.vx -= ex * f; B.vy -= ey * f;
        }
        for (i = 0; i < nodes.length; i++) {
          n = nodes[i];
          n.x = clamp(n.x + n.vx * dt, -1, 1);
          n.y = clamp(n.y + n.vy * dt, -1, 1);
          if (n.fire > 0) n.fire = Math.max(0, n.fire - dt * 2.2);
          if (n.refr > 0) n.refr -= dt;
        }

        // 3. fasciculation + pruning — traffic thickens an edge, disuse thins it
        for (e = edges.length - 1; e >= 0; e--) {
          var g = edges[e];
          g.w = clamp(g.w - EDGE_W_DECAY * dt, 0.02, 1);
          g.traffic *= Math.max(0, 1 - dt * 0.5);   // traffic is RECENT use, not a lifetime total
          if (t > PRUNE_AFTER && g.w < EDGE_PRUNE_W && g.traffic < 0.6) {
            nodes[g.a].deg--; nodes[g.b].deg--;
            edges.splice(e, 1); this.pruned++;
          }
        }

        // 4. spontaneous waves — developing networks fire before any input, to
        //    self-calibrate. This is the room's idle behaviour, not decoration.
        if (rnd() < 1.6 * dt && nodes.length) ignite((rnd() * nodes.length) | 0);
        var out = [];
        for (i = 0; i < sig.length; i++) {
          var s = sig[i]; s.u += dt * s.v;
          if (s.u >= 1) arrive(s.to, s.from); else out.push(s);
        }
        sig.length = 0;
        for (i = 0; i < out.length && i < 700; i++) sig.push(out[i]);

        // 4b. colour bleeds one hop along every filament (Jacobi-style: all deltas are
        //     computed from the same snapshot, so the result does not depend on edge
        //     order and stays deterministic).
        if (edges.length) {
          var dHue = hueDelta;
          for (i = 0; i < nodes.length; i++) dHue[i] = 0;
          for (e = 0; e < edges.length; e++) {
            var eg = edges[e], na = nodes[eg.a], nb = nodes[eg.b];
            var arc = shortArc(na.hue, nb.hue);
            var domSum = na.dom + nb.dom;
            // each side feels the OTHER's dominance share: recessive moves further
            dHue[eg.a] += arc * (nb.dom / domSum) * eg.w;
            dHue[eg.b] -= arc * (na.dom / domSum) * eg.w;
          }
          for (i = 0; i < nodes.length; i++) {
            n = nodes[i];
            var pull = clamp(BLEED * dt, 0, 0.5);
            n.hue += dHue[i] * pull;
            n.hue += shortArc(n.hue, n.hue0) * clamp(ELASTIC * dt, 0, 0.5);
            n.hue = ((n.hue % TAU) + TAU) % TAU;
          }
        }

        // 5. percolation — the headline transition. Recomputed each step (N+E is
        //    tiny) rather than kept in a union-find, because pruning removes edges
        //    and a UF cannot un-merge.
        components();
        if (this.giant >= 0.5 && this.percolatedAt < 0) this.percolatedAt = t;
        var want = this.giant >= 0.5 ? clamp((this.giant - 0.45) * 2.2, 0, 1) : 0;
        this.bloom += (want - this.bloom) * Math.min(1, dt * 0.9);
        return this;
      },

      // The field's average hue -- used for the ambient bloom, NOT a destination. The
      // lattice is not supposed to arrive here; the gradient is the point.
      meanHue: function () {
        var x = 0, y = 0;
        for (var q = 0; q < nodes.length; q++) { x += Math.cos(nodes[q].hue); y += Math.sin(nodes[q].hue); }
        return (x * x + y * y) < 1e-9 ? (nodes.length ? nodes[0].hue : 0) : Math.atan2(y, x);
      },
      // how far cells have been dragged from where they started: the seam moves, the
      // extremities do not, so the SPREAD of this is the gradient.
      drift: function () {
        var lo = Math.PI, hi = 0, sum = 0;
        for (var q = 0; q < nodes.length; q++) {
          var d = driftOf(q);
          if (d < lo) lo = d; if (d > hi) hi = d; sum += d;
        }
        return nodes.length ? { min: lo, max: hi, mean: sum / nodes.length } : { min: 0, max: 0, mean: 0 };
      },
      driftOf: driftOf,
      // how far apart the field still is, as the widest gap on the circle (radians).
      // TAU-ish while it is a rainbow of islands, 0 once one lattice owns every cell.
      hueSpread: function () {
        if (!nodes.length) return 0;
        var hs = [], q;
        for (q = 0; q < nodes.length; q++) hs.push(((hueOf(q) % TAU) + TAU) % TAU);
        hs.sort(function (u, v) { return u - v; });
        var widest = hs[0] + TAU - hs[hs.length - 1];
        for (q = 1; q < hs.length; q++) widest = Math.max(widest, hs[q] - hs[q - 1]);
        return Math.max(0, TAU - widest);     // the arc the field actually occupies
      },
      hueOf: hueOf,
      // a hue's pixels: fixed pleasing lightness, the most chroma sRGB holds there
      colorAt: function (hue) { return vivid(hue); },

      stats: function () {
        return { t: this.t, nodes: nodes.length, edges: edges.length, tips: tipCount(),
                 hue: this.meanHue(), hueSpread: this.hueSpread(),
                 drift: this.drift(),
                 giant: this.giant, comps: this.comps, locks: this.locks,
                 pruned: this.pruned, bloom: this.bloom, percolatedAt: this.percolatedAt };
      },

      // ── render: the only part that touches a canvas ───────────────────────────
      // opts (optional, used when the party director drives this): { M, alpha }.
      // M is the director's placement affine (see organisms.js) so the organism grows out
      // with the others instead of sitting in its own centred disc; alpha is the mode's
      // effective weight. Called with neither (the standalone lab) it behaves as before.
      draw: function (ctx, W, H, palette, opts) {
        if (!ctx) return;
        var M = opts && opts.M, alpha = (opts && opts.alpha != null) ? clamp(opts.alpha, 0, 1) : 1;
        if (alpha <= 0) return;
        // Colour is generated, not sampled: every pixel below is vivid(hue), so the
        // field is a full rainbow and no blend can land on grey. The palette argument is
        // still accepted (party integration will want it) but drives nothing here yet.
        var tint = vivid;
        var R = M ? M.R : Math.min(W, H) * 0.46;
        var cx = M ? M.cx : W / 2, cy = M ? M.cy : H / 2;
        var px = M ? function (x, y) { return M.px([x, y]); }
                   : function (x, y) { return [cx + x * R, cy + y * R]; };
        var i, k, e, n;

        ctx.save();
        ctx.globalCompositeOperation = "lighter";

        // the percolation payoff: the whole field warms when one lattice wins
        if (this.bloom > 0.01) {
          var bg = ctx.createRadialGradient(cx, cy, 0, cx, cy, R * 1.6);
          var bc = tint(self.meanHue());     // the bloom is the field's average, softly
          bg.addColorStop(0, rgba(bc, 0.16 * this.bloom * alpha));
          bg.addColorStop(1, rgba(bc, 0));
          ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H);
        }

        // filopodia — thin, searching, dimmer the longer they have failed
        ctx.lineWidth = Math.max(0.5, R * 0.0016);
        for (i = 0; i < nodes.length; i++) {
          n = nodes[i];
          for (k = 0; k < n.tips.length; k++) {
            var tp = n.tips[k];
            var p0 = px(n.x, n.y);
            var p1 = px(n.x + Math.cos(tp.a) * tp.len, n.y + Math.sin(tp.a) * tp.len);
            var fade = clamp(1 - tp.len / TIP_MAX, 0.15, 1);
            ctx.strokeStyle = rgba(tint(hueOf(n.id)), 0.30 * fade * alpha);
            ctx.beginPath(); ctx.moveTo(p0[0], p0[1]);
            // a probe is not a ruler: bow it slightly, on its own seeded phase
            var mx = (p0[0] + p1[0]) / 2, my = (p0[1] + p1[1]) / 2;
            var nx = -(p1[1] - p0[1]), ny = (p1[0] - p0[0]);
            var bow = (noise(n.id * 13 + k, this.t * 0.4) - 0.5) * 0.22;
            ctx.quadraticCurveTo(mx + nx * bow, my + ny * bow, p1[0], p1[1]);
            ctx.stroke();
          }
        }

        // locked filaments — width IS the fasciculation, hue IS the component
        for (e = 0; e < edges.length; e++) {
          var g = edges[e], A = nodes[g.a], B = nodes[g.b];
          var pa = px(A.x, A.y), pb = px(B.x, B.y);
          var mx2 = (pa[0] + pb[0]) / 2, my2 = (pa[1] + pb[1]) / 2;
          var nx2 = -(pb[1] - pa[1]), ny2 = (pb[0] - pa[0]);
          var sag = (noise(g.a * 101 + g.b, this.t * 0.15) - 0.5) * 0.14;
          ctx.lineWidth = Math.max(0.6, R * (0.0018 + 0.006 * g.w));
          ctx.strokeStyle = rgba(tint(hueOf(A.id)), (0.18 + 0.5 * g.w) * alpha);
          ctx.beginPath(); ctx.moveTo(pa[0], pa[1]);
          ctx.quadraticCurveTo(mx2 + nx2 * sag, my2 + ny2 * sag, pb[0], pb[1]);
          ctx.stroke();
        }

        // travelling pulses
        for (i = 0; i < sig.length; i++) {
          var s2 = sig[i], SA = nodes[s2.from], SB = nodes[s2.to];
          if (!SA || !SB) continue;
          var p = px(lerp(SA.x, SB.x, s2.u), lerp(SA.y, SB.y, s2.u));
          ctx.fillStyle = rgba(tint(hueOf(s2.from)), 0.9 * alpha);
          ctx.beginPath(); ctx.arc(p[0], p[1], R * 0.005, 0, TAU); ctx.fill();
        }

        // somata — additive halos, brighter with degree, flaring when they fire
        for (i = 0; i < nodes.length; i++) {
          n = nodes[i];
          var q = px(n.x, n.y);
          var rr = R * (0.006 + 0.012 * Math.pow(Math.min(n.deg, 6) / 6, 0.6)) * (1 + n.fire * 1.6);
          var c3 = tint(hueOf(n.id));
          var gg = ctx.createRadialGradient(q[0], q[1], 0, q[0], q[1], rr * 2.6);
          gg.addColorStop(0, rgba(c3, (0.34 + 0.52 * n.fire) * alpha));
          gg.addColorStop(1, rgba(c3, 0));
          ctx.fillStyle = gg;
          ctx.beginPath(); ctx.arc(q[0], q[1], rr * 2.6, 0, TAU); ctx.fill();
        }
        ctx.restore();
      }
    };

    // ── internals ───────────────────────────────────────────────────────────────
    function tipCount() { var c = 0; for (var q = 0; q < nodes.length; q++) c += nodes[q].tips.length; return c; }

    function contact(n, tip) {
      var ex = n.x + Math.cos(tip.a) * tip.len, ey = n.y + Math.sin(tip.a) * tip.len;
      var best = -1, bd = TOUCH_R * TOUCH_R;
      for (var q = 0; q < nodes.length; q++) {
        if (q === n.id) continue;
        var dx = nodes[q].x - ex, dy = nodes[q].y - ey, d2 = dx * dx + dy * dy;
        if (d2 < bd && nodes[q].deg < MAX_DEG && !linked(n.id, q)) { bd = d2; best = q; }
      }
      return best;
    }
    function linked(a, b) {
      for (var q = 0; q < edges.length; q++) {
        if ((edges[q].a === a && edges[q].b === b) || (edges[q].a === b && edges[q].b === a)) return true;
      }
      return false;
    }
    // touch-and-lock: the release beat. The edge is born already carrying a pulse.
    function lock(n, m) {
      edges.push({ a: n.id, b: m.id, w: 0.30, traffic: 1, born: self.t });
      n.deg++; m.deg++;
      self.locks++;
      n.fire = Math.max(n.fire, 0.6); m.fire = Math.max(m.fire, 0.6);
      sig.push({ from: n.id, to: m.id, u: 0, v: 1.4 });
    }
    function ignite(i) { if (nodes[i] && nodes[i].refr <= 0) arrive(i, -1); }
    function arrive(i, from) {
      var n = nodes[i];
      if (!n || n.refr > 0) return;
      n.fire = 0.5; n.refr = 0.34;
      for (var q = 0; q < edges.length; q++) {
        var g = edges[q], other = g.a === i ? g.b : (g.b === i ? g.a : -1);
        if (other < 0 || other === from) continue;
        // activity-dependent strengthening: a used edge thickens and survives
        g.w = clamp(g.w + EDGE_W_GAIN * 0.12, 0.02, 1);
        g.traffic++;
        if (sig.length < 700) sig.push({ from: i, to: other, u: 0, v: 1.3 });
      }
    }
    // connected components by BFS; giant = largest / N.
    function components() {
      var adj = [], q, e;
      for (q = 0; q < nodes.length; q++) { adj.push([]); nodes[q].comp = -1; }
      for (e = 0; e < edges.length; e++) { adj[edges[e].a].push(edges[e].b); adj[edges[e].b].push(edges[e].a); }
      var c = 0, biggest = 0;
      for (q = 0; q < nodes.length; q++) {
        if (nodes[q].comp >= 0) continue;
        var stack = [q], size = 0;
        nodes[q].comp = c;
        while (stack.length) {
          var v = stack.pop(); size++;
          for (var k2 = 0; k2 < adj[v].length; k2++) {
            var w = adj[v][k2];
            if (nodes[w].comp < 0) { nodes[w].comp = c; stack.push(w); }
          }
        }
        if (size > biggest) biggest = size;
        c++;
      }
      self.comps = c;
      self.giant = nodes.length ? biggest / nodes.length : 0;
    }

    components();
    return self;
  }

  var API = { create: create, sampleHist: sampleHist, gauss: gauss, valueNoise: valueNoise };
  if (typeof window !== "undefined") window.WIRING = API;
  if (typeof module !== "undefined" && module.exports) module.exports = API;
})();
